# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en"
title                    : "Jekyll Atom Theme"
url                      : https://mitchellcash.github.io # the base hostname & protocol for your site e.g. "https://mitchellcash.github.io"
baseurl                  : "/jekyll-atom-theme" # the subpath of your site, e.g. "/blog"

# Site Author
author:
  name             : "Your Name"
  github           : "mitchellcash/jekyll-atom-theme"
